version: "3"
services:
  app:
    container_name: zoomies
    restart: always
    build:
      context: .
      dockerfile: dockerfile.dev
    env_file: local.env
    ports:
      - "80:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
  db:
    container_name: zoomies-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
